import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[font]
size = 20

[font.normal]
family = "Inconsolata"
style = "Regular"

[window]
decorations = "None"
opacity = 0.9
blur = true
startup_mode = "Maximized"

[window.padding]
x = 7
y = 0
